name: booking_hotel
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter 
  shared_preferences: ^2.0.15
  firebase_database: ^9.1.4
  cloud_firestore: ^3.4.7
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  firebase_image: ^1.1.1
  firebase_dart: ^1.0.11
  cached_network_image: ^3.2.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - pic_grand_legi.jpg