// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA93y_U1K8IcPcde50P2RSdJqOrxfdNkdE',
    appId: '1:595222579767:web:3f38ce05e9691c55238db2',
    messagingSenderId: '595222579767',
    projectId: 'booking-hotel-5a52a',
    authDomain: 'booking-hotel-5a52a.firebaseapp.com',
    storageBucket: 'booking-hotel-5a52a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAJCa6uwDcmcKwxRlOFYI5xZmLCeyvFs4',
    appId: '1:595222579767:android:c6f8e5a1dedf5b8b238db2',
    messagingSenderId: '595222579767',
    projectId: 'booking-hotel-5a52a',
    storageBucket: 'booking-hotel-5a52a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDtdX7g6N298MbK4CTkDow-anph_7j0Xs',
    appId: '1:595222579767:ios:8a7759063ccd3b53238db2',
    messagingSenderId: '595222579767',
    projectId: 'booking-hotel-5a52a',
    storageBucket: 'booking-hotel-5a52a.appspot.com',
    iosClientId: '595222579767-a0e8d3i59s9vkukqsbt8157eoi5pfnd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDtdX7g6N298MbK4CTkDow-anph_7j0Xs',
    appId: '1:595222579767:ios:8a7759063ccd3b53238db2',
    messagingSenderId: '595222579767',
    projectId: 'booking-hotel-5a52a',
    storageBucket: 'booking-hotel-5a52a.appspot.com',
    iosClientId: '595222579767-a0e8d3i59s9vkukqsbt8157eoi5pfnd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingHotel',
  );
}
